### ISSUE TITLE
Image pushes out site width on mobile

### ISSUE THREAD

**Issue by nkantar** [storyscript/storyscript.io#68]
![57F105B4-4856-4646-AF61-2A7500BD1D6A](https://user-images.githubusercontent.com/568543/57178548-2806b000-6e40-11e9-9f1c-1728edef3d3b.png)

Device: iPhone X
OS: iOS 12.2
Browser: Mobile Safari

**Comment by JeanBarriere** [comment]
Hi @nkantar !

Thanks for reporting this issue !
As we are moving forward a new layout for the landing, this will be updated in a more global pull request.

**Comment by nkantar** [comment]
@JeanBarriere Sounds good, closing then. :)
